#!/bin/bash

sudo rm -rv ArcMenu
git clone --single-branch --branch gnome-42/43/44 https://gitlab.com/arcmenu/ArcMenu.git
cd ArcMenu
make install
cd ..
sudo rm -rv ArcMenu
sudo rm -rv /usr/share/gnome-shell/extensions/arcmenu\@arcmenu.com
sudo mv -v ~/.local/share/gnome-shell/extensions/arcmenu\@arcmenu.com/ /usr/share/gnome-shell/extensions
