#!/bin/bash

modules=(
	about
	add-apt-repositories
	remove-apt-packages
	install-apt-packages
	enable-broadcom-sta-dkms-driver
	enable-gnome-extensions
	copy-aliases-file-to-home-directory
	create-empty-file-template
	add-flatpak-repositories
	install-flatpak-packages
	script-finished
)
