#!/bin/bash

source header

# Ensure that all registered modules exist before sourcing them.
for item in "${modules[@]}"; do
	if [ ! -f "$item"/main ]; then
		echo "Module $item does not exist. Exiting..."
		exit
	fi
done

initial_directory=$(pwd)
last_exit_code=0

# Source the modules sequentially. Stop on error.
for item in "${modules[@]}"; do
	if [ $last_exit_code != 0 ]; then
		break
	fi
	
	echo
	echo "Now executing $item"
	cd "$item"
	source main
	last_exit_code=$?
	cd "$initial_directory"
done
