#!/bin/bash

extensions=(
	appindicatorsupport@rgcjonas.gmail.com
	hidetopbar@mathieu.bidon.ca
	caffeine@patapon.info
	dash-to-dock@micxgx.gmail.com
	no-overview@fthx
	gsconnect@andyholmes.github.io
	just-perfection-desktop@just-perfection
)
