#!/bin/bash

wget -nc -O Hack.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip

unzip -o Hack.zip

target_dir=/usr/share/fonts/truetype/hacknerd

sudo mkdir -p ${target_dir}

sudo mv -v *.ttf ${target_dir}

sudo fc-cache -fv

rm -rv Hack.zip
