#!/bin/bash

origin="$(pwd)"

# move to config dir
cd ~/.config

# back up current config
cp -r nvim nvim.backup

# ensure the gnutls-bin apt package is installed
sudo apt install -y gnutls-bin

# clone repository
git clone https://github.com/CosmicNvim/CosmicNvim.git nvim

cd "${origin}"

echo "Run nvim to start installing cosmicnvim. If gnutls errors appear, wait for the process to finish, then press I (uppercase i). Repeat until all plugins are installed. Once all plugins are installed, press U (uppercase) to update them. Once finished, quit nvim. Cosmicnvim is now ready to use."
