#!/bin/bash

origin="$(pwd)"

# move to config dir
cd ~/.config

# back up current config
cp -r nvim nvim.backup

# clone repository
git clone https://github.com/CosmicNvim/CosmicNvim.git nvim

cd "${origin}"
