#!/bin/bash

name="Debian GNOME Bloater"
description="Please review and modify as needed every module listed in the modules array in ./header and every file they're associated with before proceeding further, as they may cause unwanted changes. Please ensure that your internet connection remains stable until the script finishes executing. Do not run with sudo, password will be asked as needed."