#!/bin/bash

name="Debian GNOME Bloater"
description="Please review every module listed in the modules array in the header file before proceeding further, as they may cause unwanted changes. Please ensure that your internet connection remains stable until the script finishes executing. Do not run with sudo, password will be asked as needed."
