#!/bin/bash

url="https://initiate.alphacoders.com/download/images5/979813/png"

output_directory_path="/debian-gnome-bloater/wallpapers" # Standard directories don't work for some reason, even with chmod 777

output_file_path="${output_directory_path}/979813.png"