#!/bin/bash

# Doesn't work sometimes. Spent the last few hours on this and still idk why

source header

wget -nc -O "${output_file_path}" "${url}"

gsettings set org.gnome.desktop.background picture-uri "file://${output_file_path}"

gsettings set org.gnome.desktop.background picture-uri-dark "file://${output_file_path}"