#!/bin/bash

source header

wget "${url}" -nc -o "${output_file_path}"

gsettings set org.gnome.desktop.background picture-uri "file://${output_file_path}"

gsettings set org.gnome.desktop.background picture-uri-dark "file://${output_file_path}"