#!/bin/bash

source header

sudo wget -nc -o "${output_file_path}" "{$url}"

gsettings set org.gnome.desktop.background picture-uri "file://${output_file_path}"

gsettings set org.gnome.desktop.background picture-uri-dark "file://${output_file_path}"