#!/bin/bash

source header

wget -O gnome-shell-extension-installer "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
chmod +x gnome-shell-extension-installer
sudo mv gnome-shell-extension-installer /usr/bin

for id in "${ids[@]}"; do
	sudo gnome-shell-extension-installer --yes $id
done

echo "Extensions installed. If any of them doesn't show up, remove either the version installed in ~/.local/share/gnome-shell/extensions/ or /usr/share/gnome-shell/extensions/."
