#!/bin/bash

# Source: https://www.mongodb.com/docs/compass/current/install/.

source header

wget https://downloads.mongodb.com/compass/mongodb-compass_${version}_amd64.deb

sudo dpkg -i mongodb-compass_${version}_amd64.deb

rm -v mongodb-compass_${version}_amd64.deb

echo "MongoDB Compass installed. To use it, execute 'mongodb-compass'."
