#!/bin/bash
packages=(
	linux-image-$(uname -r|sed 's,[^-]*-[^-]*-,,')
	linux-headers-$(uname -r|sed 's,[^-]*-[^-]*-,,')
	broadcom-sta-dkms
	neofetch
	htop
	git
	l3afpad
	flatpak
	gnome-software-plugin-flatpak
	gnome-shell-extension-appindicator
	gnome-shell-extension-autohidetopbar
	gnome-shell-extension-caffeine
	gnome-shell-extension-dashtodock
	gnome-shell-extension-desktop-icons-ng
	gnome-shell-extension-gsconnect
	gnome-shell-extensions-extra
)
