" Use narrower tab width.
" Found on https://stackoverflow.com/a/57708527. 
set tabstop=2
set shiftwidth=2

" Turn on auto indent.
" Found on https://unix.stackexchange.com/a/19946.
set autoindent

" Turn on smart indent, i.e. automatically insert an indent after braces, parentheses, etc.
" Found on https://stackoverflow.com/a/59860142
set smartindent

" Automatically close braces, parentheses, quotation marks, etc.
" Found on https://stackoverflow.com/a/34992101.
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O


